enaqx/awesome-react

README.md
Added http://buildwithreact.com/ to tutorial list
=> added buildwithreact.com site

README.md
adding React-Flux, ReactPhonegap, React-Topcoat
=> adding React-Flux, ReactPhonegap, React-Topcoat

README.md
http://pomax.github.io/?#gh-weblog-1420592591221
=> Taking React to the next level: Mixins, Gulp, and Browserify

README.md
http://www.tuxedojs.org/  -- npm tuxx  -- Tuxx is a feature complete framework built on the React view layer, Flux Architecture, and CommonJS modules. Get all the performance benefits of React with the semantic abstraction and power of Tuxx.
=> Add tuxx to libraries section.

README.md
Just updated the reactiflux landing page.
=> update reactiflux landing page

README.md
Fix the URL for reactjsnewsletter.com (Add http://)
=> Fix Newsletter URL

README.md
Added new blog post titled "React + Flux Backed by Rails API"
=> Added "React + Flux Backed by Rails API"

README.md
Added nice writing React in CoffeeScript article.
=> Add react patterns

README.md
[What You Need to Know About React](http://revelry.co/2014/11/01/what-you-need-to-know-about-react/)  The page is broken
=> Removed the broken Link -

README.md
Added JSX alternatives for DSL.
=> Added JSX alternatives.

README.md
Demo here: http://mandarinconlabarba.github.io/react-tree-menu/example/index.html
=> Added in react-tree-menu

README.md
from http://ryanclark.me/getting-started-with-flux/
=> Add Introduction to Facebook's Flux architecture

README.md
We have no immutableJS examples.
=> Add ImmutableJS example.

README.md
Example here: https://github.com/olebedev/go-react-example
=> Serverside render React app on Golang

README.md
Add learnreact.com to 'video tutorials'
=> Add learnreact.com to 'video tutorials'

README.md
> Radium is a set of tools to manage inline styles on React elements. It gives you powerful styling capabilities without CSS.
=> Add Radium to React styling category

README.md
Added react-isomorphic-starterkit.
https://github.com/RickWong/react-isomorphic-starterkit
=> Added react-isomorphic-starterkit

README.md
=> remove unnecessary spaces

README.md
Added template engines section - for now only `react-templates`
=> Added template engines section

README.md
https://github.com/banyan/react-autolink
=> Add react-autolink

README.md
https://github.com/banyan/react-emoji
=> Add react-emoji

README.md
and some misplaced gaps removed
=> Component react-portal added

README.md
A minimal skeleton for building testable React apps using ES6
https://github.com/pheuter/essential-react
=> Add essential-react 

README.md
Added `react-to-html-webpack-plugin` and `static-site-generator-webpack-plugin`.
=> Add webpack plugins

README.md
=> Fix rackt GH handle

README.md
Added "React Mixins Explained By Example" tutorial
=> Added React Mixins Explained By Example tutorial

README.md
=> Added some Haskell-React resources

README.md
Added [react-datagrid](https://github.com/zippyui/react-datagrid) component
=> Added react-datagrid component

README.md
... and fixed the descriptions of some of my other components.
=> added react-inline

README.md
* [Server-rendered React + Flux in Rails](https://github.com/nambrot/rails-webpack-react-flux)
=> Server-render React + Flux in Rails

README.md
Add new section to Comprehensive Guide to Building Apps with React
=> Add part 3 in series

README.md
The article is "Best practices for building large React applications", posted on May 07, 2015 by Alex Lopatin
=> Added a very useful article on React best practices

README.md
This talk has a lot of great stuff :)
=> Add React.js on Rails video

README.md
=> Added Maple.js library to 'Libraries' section

README.md
- Isomorphic flux with alt
- ImmutableJS
- Deployable to Heroku
- Using MongoDB
- Build task with webpack
=> Add react-webpack-node to the mix.

README.md
=> add React and ClojureScript - Re-frame 

README.md
Tool which can be used to create working prototype using any set of React components
=> Add react-ui-builder

README.md
Hi,
I've worked through the book and the first version is complete. I will likely do smaller tweaks to it but I believe it should be stable enough for your list now.
Thanks!
=> Add SurviveJS - Webpack and React

README.md
Adding real world open source react apps
=> add open source apps

README.md
Adding link to Mozilla's payments-ui
=> add mozilla's payments-ui app

README.md
=> Add a layout component

README.md
I added a tutorial ["React.js Introduction For People Who Know Just Enough jQuery To Get By."](http://reactfordesigners.com/labs/reactjs-introduction-for-people-who-know-just-enough-jquery-to-get-by/)
It leads you through step-by-step how to create a "Tweet Box" and is aimed at beginners who understand the basics of jQuery.
=> add react.js tutorial for beginners

README.md
I've added a rather lengthy article about building a simple Flux application from a total scratch. I'm the author here.
Please add it if it passes quality standards.
Thank you!
=> Added 'React with Flux by example - a simple Todo List dissected'

README.md
I'd be really happy if I can add my rather big article about testing approaches used to test React components.
Thank you in advance!
=> Added "Approaches to testing React components - an overview"

README.md
@enaqx Not sure if it's okay to put it in the beginning :smile: 
Let me know if not, I can update the PR.
=> doc(Readme): add Belle component library

README.md
Let me know if the quality isn't high enough or there's anything else I can do.
The react tut involves moving through the basics with examples. After that, the tutorial presents a specification for an application and asks the reader to build it using the knowledge gained from the earlier examples. A final version and es6 version is available on other branches.  
The flux tut somewhat builds on the react tut - it introduces the reader to the key concepts in flux, then takes an application built completely with react, and guides the user through how they might go about implementing the flux pattern. It then asks them to convert the rest of the application themselves, with some pointers. The aim is to start with what the reader already knows, and demonstrate to them what flux is through …
=> React & Flux tutorial

README.md
https://github.com/sindresorhus/awesome/issues/253
=> Add awesome badge.

README.md
At Reddit, a subreddit is not stylized with a capital R in reddit.
=> Fix Subreddit stylization

README.md
... another alternative to manage css in react components
=> added react easy style

README.md
I'd like to ask to add my new blogpost to the list if it follows the quality standards.
Thank you!
=> Added "Pros and Cons of using immutability with React.js" blogpost

README.md
Adding Slack community channel to **React Community** section :)
=> Add React Slack to communities

README.md
Added React Native Module for Android Text To Speech
=> Added React Native Module for Android Text To Speech

README.md
=> add some nuclearjs stuff

README.md
@enaqx @browniefed 
Have had a decent number of people find this useful - figured it may be useful to be in here
=> add react-experiments to components

README.md
@browniefed accidentally put this under libraries instead of components
=> react-experiments should be under components not libraries

README.md
react-slide-deck: A simple react component for swipe, tabs, carousel, one page scroll ..., with animation hooks. tweening, tween callbacks. works on PC and touch devices
=> Add Component:react-slide-deck

README.md
I made a starter kit to benefit people who are trying to break into React and Webpack, and added it to the boilerplate section of the readme.
=> Add A React / Webpack Starter for Beginner

README.md
This uses portals to animate React.js DOM changes by using JavaScript portals. It's especially effective with position changes. This is an effect that is easily done with React, with the introduction of the virtual DOM. 
Please see the below video for why react-magic-move is great.
https://youtu.be/z5e7kWSHWTg?t=9m36s
=> Add react-magic-move to components

README.md
@browniefed  Here is new pull request...
=> Add Component react-listview-sticky-header

README.md
@browniefed Here is another component for creating listview with expandable section headers using react-motion
=> Add Component react-expandable-listview

README.md
I've developed a vim plugin to review babeljs transformations that comes handy
to check syntax errors on jsx files.
This might be interesting to someone else.  Anyway, thank you for this great
reference repo.
:+1
=> Add vim-babel to check jsx transformations

README.md
Add React Starterify under the Boilerplates section.
=> Add React Starterify

README.md
This is a well written port of a popular PluralSight demo application, offering a how-to with CRUD operations, and handling a Form using Flux architecture.
This application uses the following technologies:
React
React Router
Flux
Node
Webpack
Bootstrap
Essentially, a great React / Flux starter app with webpack, hot redeployment, and eslint baked in. Fully written in ES6 / ES7 with Babel support via webpack.
=> Added react-babel-webpack CRUD demo app

README.md
Those are awesome tutorials, both React, Redux and some ES6-7
=> Added Egghead Redux series link

README.md
Added link to the newly released Pro React book.
=> Added Pro React book

README.md
=> Add react-markdown-area component to the list please!

README.md
I like this talk because Pete Hunt explains the virtual DOM using drawing a stick figure as an analogy.
=> Add "Immediate Mode UIs with React" talk

README.md
This adds the [React-iCheck](https://github.com/luqin/react-icheck) component to the list of components
iCheck components built with React. Highly customizable checkbox, radio buttons and radio group. https://luqin.github.io/react-icheck
=> Add React-iCheck component. Highly customizable checkbox, radio buttons and radio group.

README.md
I've set up a React development environment in the cloud and provide free hosting that might be helpful for the ones who'd like to create and share a quick React app. 
Anyways - thanks for the list. Found quite a few interesting things :+1:
=> Add React Development Environment in the Cloud - closeheat

README.md
There is a fifth tutorial available at [Make a Mobile App with ReactJS in 30 Minutes](https://scotch.io/tutorials/make-a-mobile-app-with-reactjs-in-30-minutes).
=> Added fifth tutorial in scotch.io tutorial series

README.md
This adds the [React Sidebar](http://balloob.github.io/react-sidebar/example/) component to the list of components
=> Add React Sidebar component

README.md
[google-map-react - Isomorphic google map React component](https://github.com/istarkov/google-map-react)
=> Add Isomorphic Google Map React Component

README.md
There's a few modules around that help to find components in various ways and help a bit with shallow rendering. Would be good to put a lot more focus on testing react components in real world scenarios beyond jest.
=> Add more focus on testing

README.md
=> Add react-joyride

README.md
Added [@wesbos](https://github.com/wesbos)'s video course
=> Added video course

README.md
Added a link to a react redux boilerplate
=> added react-redux boilerplate

README.md
Added a book I'm writing to the books section.
=> Add "Thinking In React" to books section

README.md
=> Add Reduxible

README.md
=> Added React-DnR component

README.md
Add my base extended React boilerplate to the list.
=> Modern React ES6 boilerplate for everyday use.

README.md
Add React Storybook to the list - https://github.com/kadirahq/react-storybook
=> Add React Storybook

README.md
Added two components that are plug and play for authenticating to social media platforms (google and facebook)
=> Added react-facebook-login-component & react-google-login-component

README.md
Reactotron: Control, monitor, and instrument your React DOM and React Native apps. From the comfort of your TTY.
=> Add Reactotron into debug

README.md
Adding [Keo](https://github.com/Wildhoney/Keo) :+1:
=> Added Keo to 'libraries' section

README.md
> Excellent explainer of why GraphQL uses Variables. TL;DR: No injection issues and more static-time knowledge. 
- [@leeb on twitter](https://twitter.com/leeb/status/716049152321261568)
=> Adds Clay Allsopp's tutorial on GraphQL variables

README.md
Add the react+d3.js book link in Books section.
=> Add react+d3.js in Books section

README.md
- [react-component - A Collection of React UI Components](http://react-component.github.io/badgeboard/)
- [Ant Design - An enterprise-class UI design language and React-based implementation](https://github.com/ant-design/ant-design)
=> Add react-component and Ant Design of React

README.md
Just as a note, the UniversalRelayBoilerplate is the re-creation of Isomorphic Material Relay Starter Kit. Isomorphic Material Relay Starter Kit will not be developed any further and will be left as is for reference, and in case someone needs a version of the project with separate React and React Native.
UniversalRelayBoilerplate will be developed in the future, this is why I am also closing https://github.com/enaqx/awesome-react/pull/416
=> Added UniversalRelayBoilerplate

README.md
Added on a feature branch this time.
=> Add react-tsx-starter - Isomorphic React TypeScript Starter

README.md
Hey, I'm trying to get more exposure. Hope I can add this?! :)
Thanks!
=> Add `react-text-mask`

README.md
`rebass` is a nice state-less components library for React.js.
- https://github.com/jxnblk/rebass
- http://jxnblk.com/rebass/
=> Added 'rebass' components library

README.md
[The missing piece to the React testing puzzle](https://medium.com/@bruderstein/the-missing-piece-to-the-react-testing-puzzle-c51cd30df7a0#.316ec5yo9)
=> Added another React Testing tutorial.

README.md
Added link to category React General Tutorials for React Tutorial: Cloning Yelp, an epic how to,
=> Added React Tutorial: Cloning Yelp

README.md
See http://glennreyes.github.io/react-countup
=> Add react-countup component to list

README.md
Excel-like grid component built with React, with editors, keyboard navigation, copy & paste, and the like http://adazzle.github.io/react-data-grid/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/enaqx/awesome-react/457)
=> react data grid added

README.md
I have added ReactJS tutorials series from thinkster.io and egghead.io. Thanks
=> Additional React Tutorials Series

README.md
I have added a tutorial I wrote on an alternate pattern for calling APIs with redux.
=> Added a tutorial for redux

README.md
Added link to reduxnor (React Redux based blood donor demo application git:https://github.com/smanne/reduxnor demo: http://reduxnor.herokuapp.com)
=> Added link to reduxnor

README.md
Adding link to companion website for the new React Speed Coding book. The book covers React ES6, Redux, Enzyme, Flexbox, Firebase, and Webpack with 30+ custom components, 15 chapters, and 3 apps.
=> Add React Speed Coding book

README.md
https://github.com/kriasoft/aspnet-starter-kit - React + .NET/C#
https://github.com/kriasoft/fsharp-starter-kit - React + .NET/F#
=> Add ASP.NET Core Starter Kit /w React frontend

README.md
A set of React components implementing Google's Material Design specification with the power of CSS Modules http://www.react-toolbox.com
=> Add react-toolbox

README.md
A simple and html date countdown component for React [Demo](https://markafoni.github.io/react-livestamp/)
=> Add react-livestamp

README.md
Added react-cdk & link to the official Meteor+React guide
=> +react-cdk & official Meteor+React guide

README.md
Added reactjs-isomorphic-starterkit 
Added reactjs-typescript-isomorphic-starterkit
=> Added React Isomorphic Boilerplates

README.md
Added reference to my awesome range sliders: http://jpuri.github.io/react-range-slider/ 😄
=> adding reference to react-range-slider component

README.md
Hi,
This is a blogpost we made to help people setup a development workflow to preview their iOS & Android RN apps in their Github Pull Request. Using Fastlane, and Appetize.io.
Maybe this could be usefull for the RN community ;)
Thanks
=> Add tutorial to preview RN apps in your Github PR

README.md
[Reapop](https://github.com/LouisBarranqueiro/reapop) - A React & Redux notifications system
=> Add Reapop

README.md
Add boilerplate(react+redux+semantic UI), markdown with React, redux+react for beginners
=> Add boilerplate, markdown with React, redux+react for beginners

README.md
=> added NBAreact to list of React Native sample apps

README.md
Racket is a yeoman generator for building react/redux universal web application
=> Adding Racket

README.md
Fix two headlines
* Scotch.io React tutorials series
* Components
=> Fix headlines

README.md
Custom renderers can be useful for rendering to non-DOM surfaces, including canvas. The article also allows to pick up a higher-level understanding of how renderers work.
[no-bullshit](http://github.com/goshakkk/no-bs-react-webpack-starter) is a react webpack boilerplate cut to the minimum, as to not get in the way when starting new project. Particularly useful for beginners.
=> Add custom renderers intro & minimalistic boilerplate

README.md
CLI tools and templates for authoring React applications with a single dev dependency and zero configurations.
https://github.com/kriasoft/react-app
=> Add React App SDK (CLI tools and templates)

README.md
* GitHub: https://github.com/fahad19/tydel
* Docs: http://tydel.js.org
* React bindings: https://github.com/fahad19/tydel-react
* Examples (with demos): http://tydel.js.org/examples/index.html
=> Add tydel.js

README.md
I don't know whether MobX should get its own section, but I wanted to give it a shot, because I see a lot of people enjoying using it.
=> feat(mobx): add mobx

README.md
Adds [styled-components](https://github.com/styled-components/styled-components) to the React styling section
=> Add styled-components

README.md
Recharts has an awesome API made of purely declarative, composed components. It's based on D3, but feels totally like idiomatic react.
Check this out:
```javascript
<LineChart width={400} height={400} data={data}>
<XAxis dataKey="name" />
<Tooltip />
<CartesianGrid stroke="#f5f5f5" />
<Line type="monotone" dataKey="uv" stroke="#ff7300" yAxisId={0} />
<Line type="monotone" dataKey="pv" stroke="#387908" yAxisId={1} />
</LineChart>
```
=> Adds Recharts

README.md
https://devhints.io/react is a very useful quick reference/guide to using React.
(Disclaimer: I made this)
=> React tutorals: add devhints.io/react

README.md
Add our minimalistic boilerplate with React, Redux, Flowtype, Babel and Webpack2 to the Boilerplates section. https://github.com/nordsoftware/react-boilerplate
=> Add nordsoftware/react-boilerplate to Boilerplates

README.md
https://github.com/algolia/react-instantsearch
=> add react-instantsearch

README.md
Hi! I would like to add redux-autoform to the Forms category! 
Thank you! :smile:
=> Add redux-autoform to the Forms category

README.md
Could you add awesome [JSS](https://github.com/cssinjs/jss) library please?
Thanks!
=> Add JSS to React styling section

README.md
https://blog.larah.me/2017/04/10/react-server-side-rendering/
=> Add link to SSR blog post

README.md
Added atlaskit, atlasian's ui kit for react.
=> Added AtlasKit

README.md
ComingOrNot - an event planner based on react, react-router, redux, graphQL and serverless
=> added react-based ComingOrNot project to Example Apps

README.md
=> Add Aphrodite under styling

README.md
This is a plugin for Chai that I authored and maintain.
It is mentioned in a few links of this list, for example in [this tutorial](http://www.theodo.fr/blog/2016/03/getting-started-with-react-redux-and-immutable-a-test-driven-tutorial-part-1/).
=> Add chai-immutable to the testing utilities

README.md
Two new flux libraries have came out recently, simply adding them to the flux list.
=> Add Coflux and MobX to Flux implementations list.

README.md
ReactGo have changed its repository
=> ReactGo new repo

.idea/awesome.iml, .idea/modules.xml, .idea/vcs.xml, .idea/workspace.xml, README.md
Add boilerplate with PWA,SEO, Code-splitting, caching, Image Optimization and much more..
=> Add boilerplate with PWA,SEO, Code-splitting, caching, Image Optimization and much more..

README.md
This PR adds two more books about React to the Books column:
* The Road to learn React
* Taming the State in React
=> Add two React books

README.md
Hello,
I was wondering if you would consent to adding React Quickly, React in Action, and Isomorphic Development with JavaScript to your books section. The books are paid, but the first chapter of each can be downloaded for free (React Quickly has 4 free chapters available for download).
Thanks for your consideration.
=> Add three books to the books list

README.md
Add react-md
> This project's goal is to be able to create a fully accessible material design styled website using React Components and Sass. With the separation of styles in Sass instead of inline styles, it should hopefully be easy to create custom components with the existing styles.
https://react-md.mlaursen.com
=> Add react-md

README.md
Subtitled "A Comprehensive Guide to Test-First Development with Redux, React, and Immutable"
=> Add "Full-Stack Redux Tutorial"

README.md
Add Ignite (https://github.com/infinitered/ignite)
=> Add Ignite

README.md
A set of React Components that Implement Microsoft's UWP Design & Fluent Design.
=> Add React-UWP to README.md

README.md
Title : How to Graphql - The Fullstack Tutorial for GraphQL
Description : The free and open-source tutorial to learn all around GraphQL to go from zero to production.
=> Add How to Graphql - Tutorial Site

README.md
Added Bit - a virtual repository for exporting, storing, maintaining, managing, finding and using components across repositories. 
You can create and manage a scalable collection of React components from any context, and modify/use them across different React applications.
=> Added Bit under libraries

README.md
We've been using in production for a year now, and it's gone through many versions (now 6.0).
It is definitely not popular, but likely because it's not on any awesome lists ;)
=> Add gloss to CSS in JS

README.md
See demo here: https://marchaos.github.io/react-virtualized-sticky-tree/
=> Added https://github.com/marchaos/react-virtualized-sticky-tree

README.md
=> Remove deprecated library react-d3

README.md
A separation between the state and the application data is in place to test a more realistic situation where you do async calls to a remote API, something missing on many redux/react examples.
=> React/Redux CRUD with persistent state in Local Storage

README.md
https://github.com/zero-plus-x/neoform
=> Add NeoForm

README.md
added https://github.com/adam-hanna/react-responsive-tables
=> added adam-hanna/react-responsive/tables

README.md
Omnibar is an extensible search component for React.
Demo: https://vutran.github.io/omnibar/
=> Add Omnibar (Component)

README.md
Added [react-data-menu](https://github.com/dkozar/react-data-menu).
Regards,
Danko
=> Added https://github.com/dkozar/react-data-menu

README.md
https://github.com/yogaboll/react-switch
=> Add react-switch

README.md
docs(readme): add suicrux boilerplate - "Universal starter with ultimate hot-reloading. PWA/LL/SSR/React/Redux/i18n/Semantic-UI-React."
=> docs(readme): add suicrux [boilerplate]

README.md
Add link for [Zent](https://github.com/youzan/zent).
=> Add link for Zent

README.md
[rlist-view](https://github.com/gitpadtech/rlist-view)
=> add rlist-view to components list

README.md
A series of videos in Arabic showing how to create a react-native app.
From basic into redux+redux-saga
=> Add react-native video series in Arabic

README.md
Add react-breadcrumbs-dynamic package into components category
=> Add react-breadcrumbs-dynamic package

README.md
A Lightweight, customizable and fast Dropdown Tree Select component for React. 
https://github.com/dowjones/react-dropdown-tree-select
Demo: https://dowjones.github.io/react-dropdown-tree-select/
=> Add react-dropdown-tree-select

README.md
An awesome generator for react and firebase
=> Added React Firebase (Redux optional) generator

README.md
=> Add Hydux(an Elm-Like state manager)

README.md
https://ant.design/docs/react/introduce
=> Add Ant Design

README.md
Hello,
I am Saurabh, co-founder of Hackr.io. Hackr.io is a programming community & a great place to find the best online programming courses and tutorials. It's a one stop solution for tutorial recommendations with 5000+ tutorial of more than 140 programming languages.
I was looking at your learning resources page and found it pretty useful. I believe that Hackr.io would be really useful to the developer community in finding the right programming course/tutorial and would make a nice addition to your resource page.
Hackr is also listed on other esteemed websites like Lehigh University's resource page and official Official Python wiki page to name a few.
Thanks for the list of great resources you have compiled. Enjoy your week:)
=> A suggestion for a resource page addition

README.md
Added Iran React Telegram Group
Alos Removed Implementing Flux in Coffescript (404)
=> Added Iran React Telegram Group

README.md
Adding a free course on React and GraphQL
=> Adding a React and GraphQL course

README.md
Build an online text RPG with React and GraphQL wasn't displaying correctly.
=> Updating link

README.md
Ready to use card UI components.
A demo can be found here: https://nukeop.github.io/react-ui-cards/
=> Add react-ui-cards to components

README.md
Added new video courses for React and redux.
=> New video courses

README.md
Added GraphCMS to GraphQL tools and GraphCMS react tutorial
=> Adding GraphCMS

README.md
A library to use idangerous Swiper as a ReactJs component.
https://github.com/kidjp85/react-id-swiper
http://kidjp85.github.io/react-id-swiper/
=> Adding React-id-swiper

README.md
Added reactcomponent.io - a curated list of popular React component libraries and tools
=> update readme.md / added reacomponent.io

README.md
=> Removing http://react.run from list

README.md
https://hackr.io/tutorials/learn-react
=> Added Community Curated React Resources

README.md
=> fix: type error Apolo should be Apollo

README.md
Just finished the React FilePond component last week, it might be nice to have it featured this list.
=> Add `react-filepond` to component list

README.md
Hi All,
Creating this PR to add one example of code splitting, It's a simple app that is using React Router + React Loadable + Flux to split a module into small files with webpack.
Let me know if you have any question.
Tiarê
=>  React Example of Code Splitting 

README.md
This book teaches how to build a complete web app with React, Material-UI, Next, Express, Mongoose, and MongoDB. Thanks for reviewing!
=> add `Builder Book` to Books section

README.md
[Spectrum](https://github.com/withspectrum/spectrum) was open-sourced recently, it's a larger React codebase by the original author of `styled-components`
=> Add Spectrum to Real Apps

README.md
**GitHub:** https://github.com/react-tools/react-table
**Story/Documentation:** http://react-table.js.org
=> Added react-table

README.md
"react-masonry-css" is a fast Masonry layout powered by CSS, dependancy free
https://github.com/paulcollett/react-masonry-css
=> Added component, react-masonry-css

README.md
Added link to repo for `react-scrolltop-button`
=> added react-scrolltop-button

.idea/vcs.xml, README.md
add react router5 to routing libs
=> add react router5 to routing libs

README.md
[Ink - React for interactive command-line apps](https://github.com/vadimdemedes/ink)
=> 🌈  Added ink to React Projects

README.md
✨  Added: "Full-stack GraphQL with Apollo, Meteor & React" to React Tutorials > React & Meteor
=> Added GraphQL tutorial with Apollo, React and Meteor

README.md
Added link to repo for react-vertical-timeline-component
=> added react-vertical-timeline-component

README.md
Adding a link to Responsive React 'The Movie Database' (TMDb) App
=> Adding Responsive React 'The Movie Database' (TMDb) App

README.md
react-trend - Simple, elegant spark lines by Unsplash
https://github.com/unsplash/react-trend
=> Add react-trend

README.md
[![banner](https://user-images.githubusercontent.com/20046/40874682-a7b9d09c-6672-11e8-99c7-1c6ae190d6e6.png)](https://proppyjs.com)
* Website: https://proppyjs.com
* Docs: https://proppyjs.com/docs/introduction
* API: https://proppyjs.com/docs/api
* GitHub: https://github.com/fahad19/proppy
=> Add ProppyJS

README.md
`compose-state` is a library that composes multiple setState or getDerivedStateFromProps updaters in React.
https://github.com/tvler/compose-state
=> Add compose-state

README.md
It's a React wrapper to [Handsontable ](https://github.com/handsontable/handsontable)library (JavaScript spreadsheet).
=> Add Handsontable React wrapper

README.md
Hey! Here's my fresh React wrapper for Google reCAPTCHA with a lot of improvements comparing to other React reCAPTCHA libraries. Hope it helps someone!
=> Add reaptcha - reCAPTCHA wrapper

README.md
This article shows how to integrate isomorphic permission management library [CASL](https://github.com/stalniy/casl) into React app. Also there is [a complementary library casl-react](https://github.com/stalniy/casl/tree/master/packages/casl-react) which allows to itegrate React with CASL seamlessly.
=> docs(tutorial): adds tutorial about permission management

README.md
A really advanced boilerplate for react + redux along with a useful CLI tool to generate components, reducers, actions etc.
=> Added react-boilerplate with cra-gen CLI tool

README.md
Add job interview tools for React community
=> Add job interview tools

README.md
closes https://github.com/enaqx/awesome-react/issues/842
=> Removed deprecated mozilla/payments-ui

README.md
Please review and accept changes.
=> Added React performance guide

README.md
=> Add react-layer-stack

README.md
A reCAPTCHA bridge for React that works. 
https://github.com/douglasjunior/react-recaptcha-that-works
=> Add react-recaptcha-that-works

README.md
=> Add nice-react-layout

README.md
More info here: https://mattmezza.github.io/react-beautiful-chat
=> added react-beautiful-chat to components

README.md
WatermelonDB is a new way of dealing with user data in React Native and React web apps. It's optimized for building complex applications in React / React Native, and the number one goal is real-world performance.
=> Add WatermelonDB

README.md
Semantic helper components for rendering content with React.
=> Add react-semantic-render to components

README.md
formland - A simple, super-flexible, extensible config based form generator.
=> Add formland

README.md
It may be interesting for developers to choose the next libraries to use in projects.
=> Add react developer roadmap

README.md
We just created a library for some beautiful toast messages with React. More on.
https://cogoport.github.io/cogo-toast/
=> Add cogo-toast to React Components

README.md
I would love include resources about performance improvement and tuning. More and more developers are working on scaling React applications to fit in different conditions like weak Internet connection and PWA. It would be amazing if we can have a list of the topic to help the community.
The changes include 
-  an additional link under React Tutorials
- a list of libraries and articles in Analyzing React Performance section
=> Add "Analyzing React Performance" section

README.md
A document head manager for React
=> Add react-helmet to libraries section

README.md
add project link with description
=> add link to folio

README.md
=> Add maka.js to boilerplates

README.md
Hey I think it'll be better if instead of only the big "components" section that there is now.
Split it to a few components sections.
I started it with animation components and united all of them into the new animation components section.
Advantages:
- Less conflicts. The more splitted the readme. the less chances two different people will change the same line. Because they usually put it in the end of every category. 
- Easier to read. Cleaner and tidier. The components section is too big to actually go through it and to be useful..
Also, I want to suggest the library "react-singular-component", it's not a very popular one, but it is great in my opinion. It gives you a way to easily create a transition between two dom elements of a component.
Useful when:
- You have the same component in …
=> Sub category of components - animation components to make it tidier & a component suggestion

README.md
https://github.com/marmelab/react-admin
=> Add react-admin

README.md
The article is https://medium.com/dailyjs/react-is-slow-react-is-fast-optimizing-react-apps-in-practice-394176a11fba (popular on Medium)
=> Add reference article about react performance

README.md
https://github.com/yjose/reactjs-popup
=> Add reactjs-popup component

README.md
Rendora https://github.com/rendora/rendora is new and has been trending in github for the past few days
=> add Rendora to prerendering tools

README.md
It's better to have them separated from plain boilerplates.
=> Added new category for development toolkits and frameworks.

README.md
Added two new mapping libraries, `react-geo` and `react-leaflet`.
=> Add two new libraries to the map collection

README.md
Added a new routing library `curi`, a JavaScript routing library for use in React and other single page applications (SPA).
=> Add new routing library

README.md
https://github.com/kireerik/razzle-material-ui-styled-example
https://hackernoon.com/material-ui-get-started-fast-react-16-eea211d65308
=> Add Razzle Material-UI Styled Example and related article

README.md
A well-structured production ready Next.js boilerplate with Typescript, Redux, Express.js, Sass, Css, EnvConfig, Reverse Proxy, Bundle Analyzer.
=> Added "next-boilerplate"

README.md
https://github.com/mariusandra/pigeon-maps
=> Add pegion-maps

README.md
I did some curation work on the "real apps" section. I removed apps which hadn't been updated in a long time, or which didn't have a lot of functionality and so didn't serve as the best kinds of examples. I ended up with a great list of four, which feels just fine.
=> Curate the "real apps" section

README.md
Fixes https://github.com/enaqx/awesome-react/issues/905
=> Update year of link to Become a React Developer

README.md
Hello,
I added [KendoReact](https://www.telerik.com/kendo-react-ui/) to the components list. It is one of the popular React UI libraries.
=> Add kendo-react

README.md
closes https://github.com/enaqx/awesome-react/issues/914
=> Add react-jsx-filter

README.md
Added `react-apexcharts` - A React component for ApexCharts library under Charts category
=> Add React-ApexCharts

README.md
ClearX provides a painless way to manage the state for React application. Check this [link](https://codesandbox.io/embed/v6ln04730?fontsize=14) for a basic Todo App demo.
=> Add ClearX: Effortless React State Management

README.md
Hello! 
I add react-datepicker component.
This componet includes DatePicker, RangeDatePicker, TimePicker
=> Add react-datepicker component to component list

README.md
Hi,
I thought this book might be a good contribution to your list.
Thanks for your consideration!
Branko
=> Added React Native in Action to book list

README.md
https://github.com/Metroxe/react-border-wrapper
=> Added react-border-wrapper to Libraries

README.md
-> https://scrimba.com/g/glearnreact
=> added new tutorial

README.md
Added Finite State Machine and Statecharts Reference for state management which is efficient for modern web architect.
Reference for docs: [Docs](https://xstate.js.org/docs/)
=> Added XState

README.md
MERN: MongoDB, Nodejs , Reactjs ,Expressjs
Added repo link : [MERN Boilerplate](https://github.com/anikethsaha/MERN-Boilerplate)
- Graphql Specification link : [New Link](https://github.com/graphql/graphql-spec/tree/master/spec)
- Reactjs Discussion Forum : [New Link](https://reactjs.org/community/support.html#popular-discussion-forums)
- Reactjs FAQ Link : [New Link](https://reactjs.org/docs/faq-ajax.html)
=> Removed Invalid Links And added MERN Boilerplate 

README.md
I have added the [Syncfusion's react UI lib](https://www.syncfusion.com/react-ui-components) under the Components category.
=> Add Essential JS 2 react component

README.md
[react-svg](https://github.com/tanem/react-svg) is a React component that injects SVG into the DOM.
=> Add react-svg

README.md
[react-use-path](https://github.com/zhangkaiyulw/react-use-path) is the tiniest router on earth implemented with hooks. 
To use this router is simple:
```js
const [path, setPath] = usePath();
```
This enables further thoughts of modern react app architecture design.
=> Add react-use-path

README.md
Add course (youtube): Build a Pet Hotel Web App with React, GraphQL, NodeJS and Database using ScaffoldHub
=> Add course (youtube): Build a Pet Hotel with React

README.md
[Unform](https://github.com/Rocketseat/unform) is a performance focused library that helps you creating beautiful forms in React with the power of uncontrolled components performance and React Hooks.
=> Add Rocketseat/unform

README.md
isomor-react-app is a tool to create a react application using create-react-app, with all additional setup requiered for isomor.
isomor give the possibility to develop a web application in a single project by abstracting the layers between frontend and backend. Instead to implement an API, using REST or graphql, isomor will allow you to call the server functions directly from the UI code, without to think about the communication protocol. Isomor will take care to generate automatically those layers for you. All your code is implemented in the same folder and isomor will automatically separate them by using Babel transpiler. Since your code is tight together, there is much more consistency, this is one of the big advantage of using isomor, especially with TypeScript. It remove as well lot …
=> Add isomor-react-app

README.md
Awesome testing utility for React hooks.
https://github.com/testing-library/react-testing-library
=> Add react-hooks-testing-library

README.md
https://github.com/sindresorhus/react-extras
=> Add react-extras

README.md
I've added react-fontawesome, a popular React component library for Font Awesome 5.
=> Add react-fontawesome component library

README.md
Added the following libraries:
- react-vis.
- nivo.
- vx.
- echarts-for-react.
- Chartify.
- Semiotic.
Changed "VictoryJS" to "Victory".
=> Added some data visualization libraries

README.md
Add link to https://github.com/iamkevinwolf/formal
=> add link to formal

README.md
Add link to https://github.com/Raathigesh/majestic
=> 📄 Add majestic

README.md
Hi everyone, let me show you this component react-svg-pan-zoom that adds pan and zoom features to SVG.
DEMO: https://chrvadala.github.io/react-svg-pan-zoom
SOURCE: https://github.com/chrvadala/react-svg-pan-zoom
=> Adds react-svg-pan-zoom library

README.md
Hello!
I'd like to add my library to the list. People seem to like it so I thought it might fit well :blush: 
You tell me :wink: 
Thanks!
=> Add react-archer

README.md
I have added Hookstate library. I was not quite sure what category to put it to as it applies to multiple.
- It is modern alternative to Redux and Mobx.
- It also does local / form state management using the same engine.
- It uses unique rendering optimisation performance trick with hooks: eg.: [https://hookstate.netlify.com/performance-demo-large-table](https://hookstate.netlify.com/performance-demo-large-table)
=> Added hookstate library

README.md
Hi, please let me know if there is a more appropriate section under which to submit this tutorial!
Many thanks,
Alex
=> Add "Build a React chat app with Hooks, a pragmatic example" tutorial

README.md
Added `react-hook-form`, a library that handles form logic and validation like Formik but using React Hooks.
=> Add react-hook-form

README.md
PrimeReact is a Component Library so moved to the correct section.
=> Moved PrimeReact to Component Libraries

README.md
React-admin is popular, modular, stable, and maintained. I think it should be listed here.
Disclaimer: I'm one of the lead developers.
=> Add react-admin to the list of React frameworks

README.md
I have done some housekeeping to fix little typos, and update information that is outdated. Thanks for your time and effort on maintaining this useful repo.
=> Update outdated information and fix typo

README.md
Add component [react-parallax-tilt](https://github.com/mkosir/react-parallax-tilt)
=> Add component `react-parallax-tilt`

README.md
Adding react open doodles a Free Set of Sketchy Illustrations.
https://github.com/lunahq/react-open-doodles
=> Adding react open doodles

README.md
- add [redux-toolkit](https://github.com/reduxjs/redux-toolkit) under `Redux tools`
=> add redux-toolkit

README.md
demo: https://axmz.github.io/react-searchbox-awesome-page/
github: https://github.com/axmz/react-searchbox-awesome
=> add react-searchbox-awesome

README.md
https://www.kriasoft.com/universal-router/
A simple middleware-style router that can be used in both client-side and server-side applications.
=> Add universal router

README.md
please check https://alephjs.org
=> Add Aleph.js - The React Framework in Deno

README.md
Removes Omniscient.js as React.memo takes its place.
Closes #1121
=> Removes Omniscient.js

README.md
=> Add official CKEditor integrations

README.md
Modify list items into the format used in the early parts of the document:
```
- [awesome-react-item](https://awesome.site) - Awesome React Item Description
```
=> Consistent List Formatting

README.md
[Divjoy](https://divjoy.com) allows you to generate a custom React codebase with authentication, database, payments, and more. It is a paid tool, so of course feel free to reject if that isn't allowed.
=> Add Divjoy to React Development Tools

README.md
app allows to view real time arrivals, helps to avoid wasting time on guessing bus delays.
=> Add Bus Timetable to React Native Sample Apps

README.md
Moving the end of a parenthesis to the right place for the link to work.
And added if a Github respository is archived, only-read.
=> Some of links updated! And added info

README.md
It's a wrapper around popper.js
https://popper.js.org/docs/v2/
=> Add react-popper to components list.

README.md
Although tsdx doesn't say anything about react on the front page, react is a first class citizen for tsdx.
tsdx is a zero-config CLI for TypeScript package development.
I bootstrap a lot of my apps using tsdx and I think it should be part of this awesome list!
=> Add tsdx in starter kits

README.md
Hey 👋
This PR adds:
- [react-spectrum](https://react-spectrum.adobe.com/react-spectrum/index.html) - Adobe's collection of libraries and tools that help you build adaptive, accessible, and robust user experiences
- [react-aria](https://react-spectrum.adobe.com/react-aria/index.html) - Adobe's library of React Hooks that provides accessible UI primitives for your design system
- [remotion](https://github.com/JonnyBurger/remotion) - Create motion graphics in React
=> Add react-spectrum, react-aria and remotion

README.md
Easy Peasy is a simple state management library. It is essentially an abstraction of redux, but it's quite good for beginners.
=> Add easy-peasy to React State Management

README.md
This is a great resource for anyone trying to learning react hooks. This youtube series by Ben Awad has one video for each hook, in each video he explains how the hook works and discusses some use cases.
=> Added React Hooks Youtube playlist

README.md
A series of React.js coding challenges with a variety of difficulties. Useful as short coding exercises (questions) for interviews.
I'd also be happy with them to go under `React General Tutorials`.
Check them out at https://github.com/alexgurr/react-coding-challenges/
=> Add react-coding-challenges (interview questions)

README.md
Add Alibaba unified form solution.
=> add formily link

README.md
Uncompress is a simple library to decompress files .zip, .rar, .cbz, .cbr in React Native.
https://github.com/didisouzacosta/uncompress-react-native
=> add Uncompress to React Native libraries reference

README.md
Added few promising CSS-in-JS solutions that work very well with React.
=> Add Linaria and Stitches to React Styling section

README.md
This reverts commit ca05324be2209145e56f1eaab04c4dea75091c97.
Hookstate was already on the list.
=> Revert "Adding hookstate"

README.md
add DataSource - Library to power streaming data visualisations as used in Facebook's Flipper
=> add DataSource

README.md
Add vest validation framework 1.6k⭐️
=> Add vest validation framework

README.md
Rematch is Redux best practices without the boilerplate :: [https://rematchjs.org/](https://rematchjs.org/)
React Location is Powerful, enterprise-grade routing for React applications :: [react-location.tanstack.com](https://react-location.tanstack.com/)
=> Add Rematch and react-location

README.md
[swiper](https://github.com/nolimits4web/swiper) - Swiper provides built-in React component. Tree shakable, SSR support, typing, a11y and lot more
=> Add swiper component

README.md
Updated links for the new React site.
=> reactjs.org ---> react.dev

README.md
Add a lib to work with google places API
=> Update README.md Add react-google-autocomplete

README.md
Hey,
I've updated refine link and description. Thank you! 👊
=> docs: update refine link and description

README.md
Valtio makes state management in React simple by using a Proxy-based system to track changes in state and automatically update components. Some of its features include:
- It uses a native JavaScript Proxy for state tracking.
- Mutable API that feels like using plain JavaScript objects.
- Reactive components that re-render only when the part of the state they consume changes.
- No need for actions or reducers; you can just mutate the state directly.
- It works with vanilla JS as well, not only React.
=> Added Valtio into State Management and Data Fetching section

README.md
We have recently updated the project and domain name and I would like it to be up to date on this list. Thanks!
=> update tw-elements link

README.md
Added react-error-boundary lib, this lib support easier to catch bug and custom show error.
=> Add react error boundary

README.md
Added one more item to the react components sandboxes.
=> Added one more item to the react components sandboxes.

README.md
fixes #1412 
[mantineUI](https://mantine.dev/) is a fully featured components library featuring 100+ components, light and dark theming, and hooks.
=> feat(README.md): add MantineUI

README.md
Add simpleParallax.js ([demo](https://simpleparallax.com/)) that just release the 6.0.0 version with react version.
=> add simpleParallax.js library

README.md
=> Add React flow to react charts

README.md
Readest (https://github.com/readest/readest) is a modern, feature-rich ebook reader designed for avid readers offering seamless cross-platform access, powerful tools, and an intuitive interface. Being actively developed it has a beginner-friendly community.
=> Add Readest

README.md
Hi there,
I noticed the list was missing Radix Primitives, which is a very popular and high-quality library for building unstyled and accessible component systems. It seems like a valuable addition to the "UI Components" section.
Thanks for maintaining this great resource!
=> feat: Add Radix Primitives to UI Components list

README.md
🕹️ **8bitcn** is an open-source collection of retro 8-bit styled UI components for React, built on top of [Shadcn UI](https://ui.shadcn.com/), [Tailwind CSS](https://tailwindcss.com/), and [Radix UI](https://www.radix-ui.com/).
Perfect for developers who love pixel art, nostalgic design, or want to add some playful vibes to their app.
- 🎮 8-bit themed components with pixel-art styling
- 🧱 Built with Radix UI primitives
- 🎨 Styled using Tailwind CSS
- ⚡ Easily customizable
- 🌍 Ready for modern React projects
👉 [8bitcn.com](https://8bitcn.com)
=> Add 8bitcn-ui to the list of React component libraries in README.md

README.md
Playwright added to React Testing
=> Playwright added to React Testing
