README.md

There's a React + Flux group on Slack called Reactiflux: http://www.slackchats.com/site/contents/content/43043/2014-12-24/flux-reactjs-chat
It's pretty active everyday, and there's even a React core dev! This is great community, especially for people that already use Slack.

Add Reactifpux slack group to react community

---

README.md

Link had an extra forward slash, which broke the link.

Correct broken tuxx link in Libraries section.

---

README.md

Hi! This adds a link to Flummox, an isomorphic Flux library with zero singletons.
https://github.com/acdlite/flummox

Add link to Flummox

---

README.md

ReactLoop.org is a Google Reader / Hacker News hybrid that I've set up to keep track of React-related news. It imports links from RSS feeds curated collaboratively [on Github](https://github.com/obvio171/reactloop). I'd appreciate it if it could be added to the list of resources. Feel free to ping me if you have any questions. Thanks!

Add ReactLoop.org to list of communities

---

README.md

>Reagent provides a way to write efficient React components using (almost) nothing but plain ClojureScript functions.

Add clojurescript Reagent

---

README.md

I recently created a [wrapper](https://github.com/bradleyboy/codepen-react) for CodePen, React 0.13, and ES6, so I thought it would be nice to include a link here. Thanks!

Add link to CodePen 0.13 integration

---

README.md

sublime-react's syntax definition was deprecated, and now they just have snippets.

Correct sublime-react's description & add babel-sublime-snippets

---

examples/005_external_plugin/markdown_render.html
examples/006_with_http_server/app.jsx

https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html
https://facebook.github.io/react/docs/component-api.html#getdomnode

getDOMNode() has been deprecated. Use React.findDOMNode() instead.

---

README.md

...a project template for authoring and publishing React.js libraries based on ES6+, Babel, ESLint, Browserify, Mocha, Chai - [github.com/kriasoft/babel-starter-kit](https://github.com/kriasoft/babel-starter-kit)

Add Babel Starter Kit

---

README.md

I used a resource similar to this one to help get my React Native [audio app](https://github.com/jhabdas/lumpen-radio) off the ground and want to share it with others. You'll notice the repo is aptly named.

Adding link to additional tools for React Native

---

README.md

Go react example was deprecated and was replaced by the new one.
See: https://github.com/olebedev/go-starter-kit.

Add Golang Isomorphic Starter Kit

---

README.md

Fixes the "File Uploads" heading's formatting, which is missing a line break before it. Also fixes the link to the "File Uploads" section in the Table of Contents.

Fix "File Uploads" heading and link

---

README.md

I've released an 𝐎𝐩𝐞𝐧 𝐒𝐨𝐮𝐫𝐜𝐞 𝐒𝐨𝐟𝐭𝐰𝐚𝐫𝐞 project I call 𝑺𝒏𝒐𝒘𝒇𝒍𝒂𝒌𝒆. It's a javascript based application for both iOS and Android Devices. It is written using 𝗥𝗲𝗮𝗰𝘁𝗡𝗮𝘁𝗶𝘃𝗲, 𝗣𝗮𝗿𝘀𝗲.𝗰𝗼𝗺, 𝗥𝗲𝗱𝘂𝘅, 𝗝𝗲𝘀𝘁, 𝗜𝗺𝗺𝘂𝘁𝗮𝗯𝗹𝗲, and other technologies. This release it to help other developers learn how these 𝘁𝗲𝗰𝗵𝗻𝗼𝗹𝗼𝗴𝗶𝗲𝘀 𝘄𝗼𝗿𝗸 𝘀𝗲𝗮𝗺𝗹𝗲𝘀𝘀𝗹𝘆 𝘁𝗼𝗴𝗲𝘁𝗵𝗲𝗿 and take what used to be incredibly difficult to now be very achievable. I would consider it at this time as a "𝗯𝗼𝗶𝗹𝗲𝗿𝗽𝗹𝗮𝘁𝗲" or "𝘀𝘁𝗮𝗿𝘁𝗲𝗿" project that developers can learn from and use as their starting point

Add React-Native Starter App - Parse.com, Redux, Jest, Immutable (88% coverage)

---

README.md

I added a link to this project https://github.com/benoitvallon/react-native-nw-react-calculator which offers a starting point to build a project for mobile, desktop and website apps with the same code. Of course all the code is based on react and react native.
I thought it could be interesting to add it to this awesome list of resources. I added it in the boilerplate section, if you would prefer to have it in another section, let me know.

Add react + react native + nw boilerplate

---

README.md

I know I probably shouldn't add this to the top (or near top) of the list, but that is where ReactJS.NET, and they are in the same domain.

Added the React ASP.NET Boilerplate.

---

README.md

echarts is a canvas chart system of baidu. [https://github.com/ecomfe/echarts](https://github.com/ecomfe/echarts)
[echarts-for-react](https://github.com/hustcc/echarts-for-react) is the component for react.
DEMO: [http://git.hust.cc/echarts-for-react/](http://git.hust.cc/echarts-for-react/)

add echarts-for-react

---

README.md

Trailing slash now seems to cause HTTP error 404.

Fix link to Future of Javascript MVC Frameworks

---

README.md

This adds a boilerplate for getting started with Apollo and React.

Add react-apollo-starter-kit

---

README.md

We wrote a hands-on tutorial on test driving react native apps. We believe it goes well with rest of the content in this repo.

Add link to test driving react native application tutorial

---

README.md

Just point to the new location of the library and simplify the description

Update `react-text-mask` link and description

---

README.md

Hi, guys. [ARc](https://github.com/diegohaz/arc) is a React starter kit based on Atomic Design by Brad Frost and has appeared in 
- Rank 7 on [Mybridge's React.JS Top 10 Articles in October](https://medium.mybridge.co/react-js-top-ten-in-october-48998cdde5a3#.780m20e10)
- Rank 5 on [Top 50 Lightweight JavaScript Plugins & Libraries from 2016](https://speckyboy.com/top-50-javascript-2016/)
I think it would be a nice addition to the list.
@jashmenn

Add ARc to boilerplates

---

README.md

Link was introduced in https://github.com/enaqx/awesome-react/pull/699 – but not formatted correctly. Now it is 💐

fix: correct link for create react npm component

---

README.md

Add RemoteRetro application to Real Apps
[stride-nyc/remote_retro](https://github.com/stride-nyc/remote_retro), live at [remoteretro.org](https://remoteretro.org)
Thanks!

Add RemoteRetro application link to Real Apps

---

README.md

How to build React components for distribution on NPM seems like a pretty important thing that's missing from the tutorials section. I added two different tutorials, one of which is written by me.

Add "Building React components" section

---

README.md

Fixes the link to the ALM project which is currently pointing to a dead/parked domain. Also updates the description and drops "tools" from the name to reflect the project website.

Fix and update ALM

---

README.md

CSS in JS Playground is a live-editable comparison of a number of different CSS in JS libraries and techniques (including inline styles :/). This PR adds the link to this resource.
I can swap it to the Github link, as well, not sure which is preferable.
Let me know if there's anything else I can help with/clarify!

feat: add css in js playground

---

README.md

Remove 'Learn React by building the Hacker News front page' from Tutorials section

Remove outdated/unmaintained tutorial

---

README.md

**adobe-cep-react-create**  
create Adobe Photoshop/illustrator etc... extensions/plugins with React, Material UI, WebPack and Native Node modules.
a full opinionated boilerplate and library
https://github.com/HendrixString/adobe-cep-react-create

adobe-cep-react-create - create Photoshop plugins with react, material UI, webpack..

---

README.md

Create React apps using typescript with no build configuration. https://github.com/wmonk/create-react-app-typescript

Add create-react-app-typescript to boilerplates

---

README.md

Add (kick)starter guides for TypeScript-React projects.
Provided links:
* https://github.com/Microsoft/TypeScript-React-Starter
* https://sandstorm.github.io/typescript-react-app-kickstart-guide/
* https://basarat.gitbooks.io/typescript/docs/jsx/react.html (thanks @Haroenv )
Removed boken links:
* https://fistfulofbytes.com/graphql-and-g2sd/  (gets 502)
* https://learn.pusher.com/rpg (broken certificate)

FEATURE: Add 'React and TypeScript' tutorials

---

.travis.yml
README.md

[react material web component](https://jamesmfriedman.github.io/rmwc/) is A React wrapper for Google's official Material Components for the Web
RMWC was created to be the most performant, un-opinionated, and simple implementation of Material Design in React.
I find it myself its the simplest react wrapper of material component
the stars is still under 1k 
I think it needs more attention from react community

added React Material Web Components

---

README.md

Added my routing and static rendering library `navi`, which drives Frontend Armory and create-react-blog.
Has > 1000 stars, and is growing slowly but steadily.

Add the Navi router

---

README.md

I would like to add my article on how to use React Native with TypeScript. [(It was encouraged by the RN team.)](https://twitter.com/reactnative/status/1093515749493227521)

Add 'Using React Native With TypeScript'

---

README.md

Original page is now only a link to the new page

Updated link to moved JSX in TypeScript page

---

README.md

react-materialize is a material design framework for react, based on materializecss
https://github.com/react-materialize/react-materialize
https://github.com/Dogfalo/materialize

Add react-materialize

---

README.md

[react-typeahead-search](https://github.com/tonyspiro/react-typeahead-search) should be removed from Awesome React because:
* It is no longer maintained - newest commit is 4 years old
* README is of low quality and demo link is not working
* No other documentation then README
* No NPM / community link
* Only one person involved in library
* Library can serve only as a demonstration that autocomplete can be written using jQuery, Bootstrap and React, re-using it in any kind of project would require significant modifications

Removed react-typeahead-search

---

README.md

Added reactjsvideos.com which currently has an indexed list of 520 videos from 27 conferences.
The list is also available to view as a README at the [react-conf-videos](https://github.com/simonccarter/react-conf-videos) github repo.

Added reactjsvideos.com

---

README.md

It's just Cloudflare returning `521` for `http` requests, so it should be used `https` instead.
```bash
$ curl -I  http://creativecommons.org/publicdomain/zero/1.0/  
HTTP/1.1 521 Origin Down
$ curl -I  https://creativecommons.org/publicdomain/zero/1.0/ 
HTTP/2 200 
```

Fix creativecommons.org issue and adding react component projects based on Bulma and Tailwind CSS

---

README.md

Zeit renamed itself to Vercel. Also, zeit-ui (which is unrelated to Zeit) renamed itself to geist.

Fix links to moved repos

---

README.md

The project is stale. The last release was over a year ago and the repository has been archived.
The author was looking for co-maintainers without success: https://github.com/kevinwolfdev/formal/issues/52

Remove link to Formal

---

README.md

Changes:
- All react project starters are now moved under a new *React Starter Kits and Toolchains* category
- Added `Razzle`, `Neutrino` and `create-react-library` to *React Starter Kits and Toolchains*
fixes: https://github.com/enaqx/awesome-react/issues/1205

New *Starter Kits and Toolchains* category

---

README.md

Hi! 👋 Thanks for this project!
I added two micro-libraries:
- [wouter](https://github.com/molefrog/wouter) — a tiny 1,3 KB modern routing solution based on hooks.
- [react-colorful](https://github.com/omgovich/react-colorful) — the tiniest React color picker (14 times lighter than react-color).

Add wouter and react-colorful

---

README.md

A new 2021 styling library from the co-creator of CSS Modules - [Mark Dalgleish](https://github.com/markdalgleish).

Adding vanilla-extract library

---

README.md

The website `reactjsvideos.com` no longer is working. This removes that URL from the README.

Remove broken URL to site that doesn't exist.

---

README.md

This PR proposes adding [Intlayer](https://intlayer.org/) to the internationalization section. 
Intlayer is a modern, open-source i18n library designed to enhance maintainability in React applications by leveraging TypeScript and component-level content declarations.
- **Component-Level Content Declarations**: Intlayer allows developers to define translations directly alongside their React components. This approach keeps translations contextually relevant and simplifies maintenance as the application scales. 
- **TypeScript Integration**: With autogenerated type definitions for translation keys, Intlayer ensures type safety, providing robust autocompletion and compile-time error detection. This integration reduces runtime errors and enhances developer productivity. 
- **Seamless Vite and …

Add Intlayer to React Internationalization section

---

README.md

This PR adds Notifuse to the `React Real Apps` section.
**About Notifuse:**
- Open-source & self-hosted emailing platform for newsletters & transactional emails
- Features a React-based console interface built with React 18, TypeScript, Vite, and Ant Design
- Includes a visual email builder with MJML and an embeddable notification center widget
- Production-ready application demonstrating real-world React usage
**Links:**
- GitHub: https://github.com/Notifuse/notifuse
- Live Demo: https://demo.notifuse.com/signin?email=demo@notifuse.com
- Website: https://www.notifuse.com
**Why it fits this category:**
Notifuse is a complete, production React application showcasing modern React development practices including React Router, TanStack Query for state management, Tiptap for rich text editing, …

Add Notifuse to React Real Apps
